### PR TITLE
add leftN, rightN

### PR DESCRIPTION
**Pull request by chris-martin**
Pulled out of megarepo, seems like a convenient thing to have.

### CODE REVIEW

**Review by pbrisbin — APPROVED** [review]
Neat. Any reason to not merge the Restyled fixes?

**Comment by chris-martin** [comment]
I wasn't sure if restyled was set up properly, as that isn't our usual style.

**Comment by pbrisbin** [comment]
Ah yeah, probably need a quick convert-to-fourmolu PR for this project before going further.

**Comment by chris-martin** [comment]
Okay, the style bot appears to be behaving sensibly now.

**Pull request merged**
